import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Zylker HR | Branding Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-50">
      <div className="text-center lg:text-left max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:py-24 lg:px-24 lg:items-center lg:justify-between">
        <h2 className="text-4xl font-extrabold tracking-tight text-gray-900 lg:text-6xl">
          <span className="block">業務のムダを省き、</span>
          <span className="mt-6 block text-green-600">生産性を上げる。</span>
        </h2>
        <div className="mt-8 flex lg:flex-shrink-0">
          <div className="inline-flex rounded-md shadow">
            <a
              href="#"
              className="inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-bold rounded-md text-white bg-green-600 hover:bg-green-700"
            >
              15日間 無料トライアル
            </a>
          </div>
          <div className="ml-3 inline-flex rounded-md shadow">
            <a
              href="#"
              className="inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-bold rounded-md text-green-600 bg-white hover:bg-green-50"
            >
              資料ダウンロード
            </a>
          </div>
        </div>
      </div>
    </main>
    </div>
  )
}
