import Head from 'next/head'
import styled from 'styled-components'

export default function Home() {
   // Create a Title component that'll render an <h1> tag with some styles
   const Title = styled.h1`
   font-size: 1.5em;
   text-align: center;
   color: palevioletred;
 `;

 // Create a Wrapper component that'll render a <section> tag with some styles
 const Wrapper = styled.section`
   padding: 4em;
   background: papayawhip;
 `;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
            <Wrapper>
            <Title>
              Hello World!
            </Title>
          </Wrapper>
      </main>
    </div>
  )
}
